autoformat

diff --git a/src/openmpiscript b/src/openmpiscript
--- a/src/openmpiscript
+++ b/src/openmpiscript
@@ -73,23 +73,23 @@ EXINT=$(condor_config_val OPENMPI_EXCLUDE_NETWORK_INTERFACES)
 # Not having /tmp mounted under scratch may hang mpi jobs.
 _USE_SCRATCH=$(condor_config_val MOUNT_UNDER_SCRATCH)
 if [ -z $_USE_SCRATCH ]; then
-    >&2 echo "WARNING: MOUNT_UNDER_SCRATCH not set in condor_config"
+	echo >&2 "WARNING: MOUNT_UNDER_SCRATCH not set in condor_config"
 elif test "${_USE_SCRATCH#*/tmp}" == "$_USE_SCRATCH"; then
-    >&2 echo "WARNING: /tmp not included in MOUNT_UNDER_SCRATCH"
+	echo >&2 "WARNING: /tmp not included in MOUNT_UNDER_SCRATCH"
 fi
 
 # If MPDIR is not set, then use a default value
 if [ -z $MPDIR ]; then
-    >&2 echo "WARNING: Using default value for \$MPDIR in openmpiscript"
-    MPDIR=/usr/lib64/openmpi
+	echo >&2 "WARNING: Using default value for \$MPDIR in openmpiscript"
+	MPDIR=/usr/lib64/openmpi
 fi
 PATH=$MPDIR/bin:.:$PATH
 export PATH
 
 # If EXINT is not set, then use some default values
 if [ -z $EXINT ]; then
-    >&2 echo "WARNING: Using default values for \$EXINT in openmpiscript"
-    EXINT="docker0,virbr0"
+	echo >&2 "WARNING: Using default values for \$EXINT in openmpiscript"
+	EXINT="docker0,virbr0"
 fi
 ##
 
@@ -98,37 +98,37 @@ _orted_launcher_pid=0
 _mpirun_pid=0
 CONDOR_CHIRP=$(condor_config_val libexec)/condor_chirp
 force_cleanup() {
-    # Forward SIGTERM to the orted launcher
-    if [ $_orted_launcher_pid -ne 0 ]; then
-	kill -s SIGTERM $_orted_launcher_pid
-    fi
-
-    # Cleanup mpirun
-    if [ $_CONDOR_PROCNO -eq 0 ] && [ $_mpirun_pid -ne 0 ]; then
-	$CONDOR_CHIRP ulog "Node $_CONDOR_PROCNO caught SIGTERM, cleaning up mpirun"
-	rm $HOSTFILE
-	
-	# Send SIGTERM to mpirun and the orted launcher
-	kill -s SIGTERM $_mpirun_pid
-
-	# Give mpirun 30 seconds to terminate nicely
-	for i in {1..30}; do
-	    kill -0 $_mpirun_pid 2> /dev/null # returns 0 if running
-	    _mpirun_killed=$?
-	    if [ $_mpirun_killed -ne 0 ]; then
-		break
-	    fi
-	    sleep 1
-	done
-
-	# If mpirun is still running, send SIGKILL
-	if [ $_mpirun_killed -eq 0 ]; then
-	    $CONDOR_CHIRP ulog "mpirun hung on Node ${_CONDOR_PROCNO}, sending SIGKILL!"
-	    kill -s SIGKILL $_mpirun_pid
+	# Forward SIGTERM to the orted launcher
+	if [ $_orted_launcher_pid -ne 0 ]; then
+		kill -s SIGTERM $_orted_launcher_pid
 	fi
 
-    fi
-    exit 1
+	# Cleanup mpirun
+	if [ $_CONDOR_PROCNO -eq 0 ] && [ $_mpirun_pid -ne 0 ]; then
+		$CONDOR_CHIRP ulog "Node $_CONDOR_PROCNO caught SIGTERM, cleaning up mpirun"
+		rm $HOSTFILE
+
+		# Send SIGTERM to mpirun and the orted launcher
+		kill -s SIGTERM $_mpirun_pid
+
+		# Give mpirun 30 seconds to terminate nicely
+		for i in {1..30}; do
+			kill -0 $_mpirun_pid 2>/dev/null # returns 0 if running
+			_mpirun_killed=$?
+			if [ $_mpirun_killed -ne 0 ]; then
+				break
+			fi
+			sleep 1
+		done
+
+		# If mpirun is still running, send SIGKILL
+		if [ $_mpirun_killed -eq 0 ]; then
+			$CONDOR_CHIRP ulog "mpirun hung on Node ${_CONDOR_PROCNO}, sending SIGKILL!"
+			kill -s SIGKILL $_mpirun_pid
+		fi
+
+	fi
+	exit 1
 }
 trap force_cleanup SIGTERM
 ##
@@ -140,9 +140,9 @@ export PATH=$MPDIR/bin:$PATH
 $ORTED_LAUNCHER &
 _orted_launcher_pid=$!
 if [ $_CONDOR_PROCNO -ne 0 ]; then
-    # If not on node 0, wait for orted
-    wait $_orted_launcher_pid
-    exit $?
+	# If not on node 0, wait for orted
+	wait $_orted_launcher_pid
+	exit $?
 fi
 ##
 
@@ -150,19 +150,19 @@ fi
 # Build the hostfile
 HOSTFILE=hosts
 while [ -f $_CONDOR_SCRATCH_DIR/$HOSTFILE ]; do
-    HOSTFILE=x$HOSTFILE
+	HOSTFILE=x$HOSTFILE
 done
 HOSTFILE=$_CONDOR_SCRATCH_DIR/$HOSTFILE
 REQUEST_CPUS=$(condor_q -jobads $_CONDOR_JOB_AD -af RequestCpus)
 
-for node in $(seq 0 $(( $_CONDOR_NPROCS - 1 ))); do
-    if $USE_OPENMP; then
-	# OpenMP will do the threading on the execute node
-	echo "$node slots=1" >> $HOSTFILE
-    else
-	# OpenMPI will do the threading on the execute node
-	echo "$node slots=$REQUEST_CPUS" >> $HOSTFILE
-    fi
+for node in $(seq 0 $(($_CONDOR_NPROCS - 1))); do
+	if $USE_OPENMP; then
+		# OpenMP will do the threading on the execute node
+		echo "$node slots=1" >>$HOSTFILE
+	else
+		# OpenMPI will do the threading on the execute node
+		echo "$node slots=$REQUEST_CPUS" >>$HOSTFILE
+	fi
 done
 
 # Make sure the executable is executable
